export function getDemoUi(language?: string) {
  const isFrench = language?.startsWith('fr');

  return isFrench
    ? {
        active: 'Actifs',
        archived: 'Archiv\u00e9s',
        assistantStreaming: 'G\u00e9n\u00e9ration',
        chunks: 'fragments',
        closeSidebar: 'Fermer le panneau',
        closeReview: 'Fermer',
        confidence: 'Confiance',
        copy: 'Copier',
        currentMatch: 'correspondance active',
        emptySubtitle:
          "Fermez ce panneau pour ouvrir un espace document vide. Les sources citées y apparaîtront dès qu'une réponse référence un passage.",
        emptyTitle: 'Aucun document ouvert',
        entities: 'entit\u00e9s',
        entitySearch: 'Rechercher des entit\u00e9s',
        enterHint:
          'Entr\u00e9e pour envoyer \u2022 Maj+Entr\u00e9e pour nouvelle ligne',
        fast: 'rapide',
        findNoQuery: 'Aucune recherche',
        findNoResults: 'Aucun r\u00e9sultat',
        firstToken: 'premier token',
        folders: 'Dossiers',
        hideReasoning: 'Masquer le raisonnement',
        hideRetrieval: 'Masquer la r\u00e9cup\u00e9ration',
        justNow: "\u00e0 l'instant",
        matches: 'correspondances',
        metadata: 'm\u00e9tadonn\u00e9es',
        mobileChat: 'Chat',
        mobileDocument: 'Document',
        mobileThreads: 'Fils',
        newChat: 'Nouvelle conversation',
        newContent: 'Nouveau contenu',
        openReview: 'Essayer dans le chat',
        papers: 'Papers',
        page: 'p.',
        pages: 'pages',
        pdfSearch: 'Rechercher dans le document',
        queries: 'Requ\u00eates',
        searchResults: 'r\u00e9sultats',
        scrollToBottom: 'Aller en bas',
        sendHint: 'Cliquez sur envoyer',
        sourceAccess: 'Espace s\u00e9curis\u00e9',
        sourceAccessLabel: 'Acc\u00e8s',
        sourceFile: 'Fichier',
        sourceParser: 'Analyse PDF avec mise en page + extraction texte',
        sourceParserLabel: 'Analyse',
        sourceScope: 'Fichiers autoris\u00e9s et bases de connaissance',
        sourceScopeLabel: 'Port\u00e9e',
        chunkingLabel: 'D\u00e9coupage',
        processingLabel: 'Traitement',
        pipelineLabel: 'Pipeline',
        showReasoning: 'Afficher le raisonnement',
        showRetrieval: 'Afficher la r\u00e9cup\u00e9ration',
        thorough: 'approfondi',
        balanced: '\u00e9quilibr\u00e9',
        sourceMatch: 'correspondance texte',
        sourcePreview: 'Aper\u00e7u du surlignage texte',
        thinking: 'Raisonnement',
        today: "Aujourd'hui",
        toolCall: 'Appel outil',
        topScore: 'meilleur score',
        tourBack: 'Retour',
        tourDone: 'Terminer',
        tourNext: 'Suivant',
        tourSkip: 'Passer',
        tourSendContent:
          'La question est pr\u00eate. Cliquez sur envoyer pour voir la r\u00e9ponse se construire avec les sources.',
        tourSendTitle: 'Envoyez le message',
        tourCloseSidebarContent:
          'Fermez le panneau des fils pour gagner de la place. Vous pourrez le rouvrir \u00e0 tout moment avec le bouton lat\u00e9ral.',
        tourCloseSidebarTitle: "Lib\u00e9rez l'espace",
        tourSidebarContent:
          'Le panneau des fils garde les conversations actives et archiv\u00e9es \u00e0 port\u00e9e de main. Pour une revue documentaire, il peut \u00eatre ferm\u00e9 afin de privil\u00e9gier la r\u00e9ponse et le PDF.',
        tourSidebarTitle: 'Fils de conversation',
        tourSourcesContent:
          'Les r\u00e9f\u00e9rences ouvrent le PDF au bon endroit et gardent le passage cit\u00e9 v\u00e9rifiable.',
        tourSourcesTitle: 'Sources et PDF',
        tourPdfContent:
          "Le PDF s'ouvre directement sur la page cit\u00e9e avec un surlignage du passage source, pas seulement un num\u00e9ro de page.",
        tourPdfTitle: 'Preuve dans le document',
        tourMetadataContent:
          "Les m\u00eames fichiers peuvent \u00eatre ing\u00e9r\u00e9s par API, organis\u00e9s en dossiers, enrichis avec m\u00e9tadonn\u00e9es et r\u00e9utilis\u00e9s par vos assistants avec contr\u00f4le d'acc\u00e8s.",
        tourMetadataTitle: 'Ingestion et gouvernance',
        tourOrchestrationContent:
          'Lecture, recherche, passages retrouv\u00e9s et g\u00e9n\u00e9ration restent visibles. Ajustez les panneaux si vous voulez privil\u00e9gier le chat ou le document.',
        tourOrchestrationTitle: 'Orchestration',
        tourEntitiesContent:
          "Le rail lat\u00e9ral s'ouvre \u00e0 la demande pour inspecter entit\u00e9s, m\u00e9tadonn\u00e9es et fragments r\u00e9cup\u00e9r\u00e9s.",
        tourEntitiesTitle: "Rail d'entit\u00e9s",
        potentialInaccuracy: 'Inexactitude potentielle',
        verified: 'v\u00e9rifi\u00e9',
        waiting: 'En attente du premier token',
        you: 'Vous',
      }
    : {
        active: 'Active',
        archived: 'Archived',
        assistantStreaming: 'Generating',
        chunks: 'chunks',
        closeSidebar: 'Close sidebar',
        closeReview: 'Close',
        confidence: 'Confidence',
        copy: 'Copy',
        currentMatch: 'current match',
        emptySubtitle:
          'Close this panel to open an empty document workspace. Cited sources will appear here as soon as an answer references a passage.',
        emptyTitle: 'No document open',
        entities: 'entities',
        entitySearch: 'Search entities',
        enterHint: 'Enter to send \u2022 Shift+Enter for newline',
        fast: 'fast',
        findNoQuery: 'No query',
        findNoResults: 'No results',
        firstToken: 'first token',
        folders: 'Folders',
        hideReasoning: 'Hide reasoning',
        hideRetrieval: 'Hide retrieval',
        justNow: 'just now',
        matches: 'matches',
        metadata: 'metadata',
        mobileChat: 'Chat',
        mobileDocument: 'Document',
        mobileThreads: 'Threads',
        newChat: 'New chat',
        newContent: 'New content',
        openReview: 'Try in chat',
        papers: 'Papers',
        page: 'p.',
        pages: 'pages',
        pdfSearch: 'Search in document',
        queries: 'Queries',
        searchResults: 'results',
        scrollToBottom: 'Scroll to bottom',
        sendHint: 'Click send',
        sourceAccess: 'Secure workspace',
        sourceAccessLabel: 'Access',
        sourceFile: 'File',
        sourceParser: 'Layout-aware PDF parsing + text extraction',
        sourceParserLabel: 'Parser',
        sourceScope: 'Authorized files and knowledge bases',
        sourceScopeLabel: 'Scope',
        chunkingLabel: 'Chunking',
        processingLabel: 'Processing',
        pipelineLabel: 'Pipeline',
        showReasoning: 'Show reasoning',
        showRetrieval: 'Show retrieval',
        thorough: 'thorough',
        balanced: 'balanced',
        sourceMatch: 'text match',
        sourcePreview: 'Text highlight preview',
        thinking: 'Thinking',
        today: 'Today',
        toolCall: 'Tool call',
        topScore: 'top score',
        tourBack: 'Back',
        tourDone: 'Done',
        tourNext: 'Next',
        tourSkip: 'Skip',
        tourSendContent:
          'The question is ready. Click send to watch the answer build with sources.',
        tourSendTitle: 'Send the message',
        tourCloseSidebarContent:
          'Close the thread sidebar to make room. You can reopen it at any time with the side toggle.',
        tourCloseSidebarTitle: 'Free up space',
        tourSidebarContent:
          'The thread sidebar keeps active and archived conversations nearby. During document review, you can close it and focus on the answer plus the PDF.',
        tourSidebarTitle: 'Conversation threads',
        tourSourcesContent:
          'References open the PDF at the right passage so every claim stays verifiable.',
        tourSourcesTitle: 'Sources and PDF',
        tourPdfContent:
          'The PDF opens on the cited page and highlights the source passage, not just the page number.',
        tourPdfTitle: 'Document evidence',
        tourMetadataContent:
          'The same files can be ingested by API, organized in folders, enriched with metadata and reused by assistants with access control.',
        tourMetadataTitle: 'Ingestion and governance',
        tourOrchestrationContent:
          'Reading, search, retrieved passages and generation stay visible. Resize the panels whenever you want more room for chat or the document.',
        tourOrchestrationTitle: 'Orchestration',
        tourEntitiesContent:
          'The side rail opens on demand for entities, metadata and retrieved chunks.',
        tourEntitiesTitle: 'Entity rail',
        potentialInaccuracy: 'Potential inaccuracy',
        verified: 'verified',
        waiting: 'Waiting for first token',
        you: 'You',
      };
}
